language: python
python:
  - 2.7
before_install:
  - export PYTHONPATH=$HOME/builds/O1sims/Sukasa
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
script:
  - python manage.py runserver
