version: '2'
services:
  sukasa:
    restart: unless-stopped
    image: sukasa:latest
    container_name: sukasa
    command: python /Sukasa/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ".:/Sukasa/"
    depends_on:
      - kibana
      - elasticsearch
    networks:
      - docker-elk
    environment:
      - SUKASA_PORT=8000
      - SUKASA_HOSTNAME=sukasa
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_HOSTNAME=elasticsearch

  elasticsearch:
    restart: unless-stopped
    image: elasticsearch:latest
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - docker-elk
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    restart: unless-stopped
    image: kibana:latest
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - docker-elk
    depends_on:
      - elasticsearch

networks:
  docker-elk:
    driver: bridge
