version: '3'
services:
  nginx:
    restart: unless-stopped
    image: nginx:1.13
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/

  sukasa:
    restart: unless-stopped
    image: sukasa:latest
    container_name: sukasa
    command: python /sukasa/manage.py runserver 0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - "./backend/:/sukasa/"
    depends_on:
      - sukasa-db
    environment:
      - SUKASA_PORT=5000
      - SUKASA_HOSTNAME=sukasa
      - SUKASA_GUI_PORT=3000
      - SUKASA_GUI_HOSTNAME=localhost
      - DB_NAME=Sukasa
      - MONGO_PORT=8210
      - MONGO_HOSTNAME=sukasa-db
      - REDIS_PORT=6379
      - REDIS_HOSTNAME=sukasa-redis
      - DEVELOPMENT=True

  sukasa-gui:
    restart: unless-stopped
    image: sukasa-gui:latest
    container_name: sukasa-gui
    ports:
      - "3000:3000"
    depends_on:
      - sukasa

  sukasa-db:
    restart: unless-stopped
    image: mongo:latest
    container_name: sukasa-db
    command: mongod --port 8210
    ports:
      - "8210:8210"

  sukasa-redis:
    restart: unless-stopped
    image: redis:latest
    container_name: sukasa-redis
    ports:
      - "6379:6379"
