version: '3'
services:
  sukasa:
    restart: unless-stopped
    image: sukasa:latest
    container_name: sukasa
    command: python /sukasa/manage.py runserver 0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - "./backend/:/sukasa/"
    depends_on:
      - sukasa-db
    environment:
      - SUKASA_PORT=5000
      - SUKASA_HOSTNAME=sukasa
      - SUKASA_GUI_PORT=3000
      - SUKASA_GUI_HOSTNAME=localhost
      - DB_NAME=Sukasa
      - MONGO_PORT=8210
      - MONGO_HOSTNAME=sukasa-db
      - DEVELOPMENT=True

  sukasa-db:
    restart: unless-stopped
    image: mongo:latest
    container_name: sukasa-db
    command: mongod --port 8210
    ports:
      - "8210:8210"
